# TODO don't need to clone repo

environment:
  matrix:
    - PYTHON: "C:\\Python37"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - python -m pip install nbsmoke

build: off

test_script:
  - cd %TMP%
  - pytest -v --pyargs nbsmoke
