environment:
  matrix:
    - PYTHON: "C:\\Python37"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - python -m pip install nbsmoke

build: off

test_script:
  - xcopy /E /I tests %TMP%\\tests
  - cd %TMP%
  - python -c "import nbsmoke"
  - pytest -v tests
