sudo: false
language: python

stages:
  - lint
  - test
  - conda_test
  - name: pypi_package
    if: (branch = master AND type != pull_request) OR (tag =~ ^v)
  - name: conda_dev_package
    if: (branch = master AND type != pull_request)
  - name: conda_package
    if: tag =~ ^v

jobs:
  include:

  - &default
    stage: test
    python: 3.6
    env: TOX_ENV=py36
    install:
      - pip install tox
    script:
      - tox -e $TOX_ENV

  - <<: *default
    stage: lint
    env: TOX_ENV=flake8

  - <<: *default
    python: 2.7
    env: TOX_ENV=py27

  - <<: *default
    # like a python-using developer
    env: TOX_ENV=dev

  - <<: *default
    stage: pypi_package
    install: true
    script: true
    deploy:
      provider: pypi
      distributions: "sdist bdist_wheel"
      on:
        tags: true
      user: ceball
      password: $PYPI_PWD

  - &conda_default
    # like a conda-using developer
    stage: conda_test
    python: 3.6
    before_install:
      - pip install "pyct <0.2.1" && doit install_miniconda && rm -f .doit.db
      - export PATH="$HOME/miniconda/bin:$PATH"
      - conda install -y -c pyviz/label/dev -c conda-forge "pyct <0.2.1"
      - doit ci_configure_conda
    install:
      - doit conda_develop_install_alternate --channel=conda-forge
    script:
      - doit unit_tests

#  - <<: *conda_default
#    stage: conda_test
#    python: 2.7

  - <<: *conda_default
    stage: conda_dev_package
    install:
      - doit build_conda_package --channel conda-forge
    script:
      - doit upload_conda_package --token=$CONDA_UPLOAD_TOKEN --label=dev

  - <<: *conda_default
    stage: conda_package
    install:
      - doit build_conda_package --channel conda-forge    
    script:
      - doit upload_conda_package --token=$CONDA_UPLOAD_TOKEN --label=main --label=dev

#before_cache:
#- rm -rf $HOME/.cache/pip/log
#cache:
#  directories:
#  - "$HOME/.cache/pip"
