language: python

stages:
  - lint
  - test
  - name: pip_dev_package
    if: tag =~ ^v(\d+|\.)*[a-z]\d*$
  - name: pip_package
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$

jobs:
  include:

  - &default
    stage: test
    python: 3.7
    env: TOX_ENV=py37
    install:
      - pip install tox
    script:
      - tox -e $TOX_ENV

  - <<: *default
    stage: lint
    env: TOX_ENV=flake8

  - <<: *default
    python: 2.7
    env: TOX_ENV=py27

  - <<: *default
    python: 3.6
    env: TOX_ENV=py36

  - <<: *default
    python: 3.8
    env: TOX_ENV=py38

  - <<: *default
    # like a python-using developer
    env: TOX_ENV=dev

  - <<: *default
    # measuring coverage of a pytest plugin using pytest-cov is slightly awkward,
    # so we have a separate step for it
    env: TOX_ENV=coverage

  - <<: *default
    stage: pip_package
    install: true
    script: true
    deploy:
      provider: pypi
      distributions: "sdist bdist_wheel"
      on:
        tags: true
      user: ceball
      password: $PYPI_PWD

  - <<: *default
    stage: pip_dev_package
    install: true
    script: true
    deploy:
      provider: pypi
      server: https://test.pypi.org/legacy/
      distributions: "sdist bdist_wheel"
      on:
        tags: true
      user: ceball
      password: $PYPI_PWD
