language: python

stages:
  - lint
  - test
  - name: test_latest_release
    if: type = cron
  - name: pip_package
    if: tag =~ ^v(\d)(\d|\.)*

jobs:
  include:

  - &default
    stage: test
    python: 3.7
    env: TOX_ENV=py37
    install:
      - pip install tox
    script:
      - tox -e $TOX_ENV

  - <<: *default
    stage: lint
    env: TOX_ENV=flake8

  - <<: *default
    python: 3.6
    env: TOX_ENV=py36

  - <<: *default
    python: 3.8
    env: TOX_ENV=py38

  - <<: *default
    # like a python-using developer
    env: TOX_ENV=dev

  - <<: *default
    # measuring coverage of a pytest plugin using pytest-cov is slightly awkward,
    # so we have a separate step for it
    env: TOX_ENV=coverage

  - <<: *default
    stage: pip_package
    install: true
    script: true
    deploy:
      provider: pypi
      distributions: "sdist bdist_wheel"
      on:
        tags: true
      user: ceball
      password: $PYPI_PWD

  # TODO: don't need to clone the repo
  - stage: test_latest_release
    python: 3.7
    install:
      - pip install nbsmoke
    script:
      # TODO: when pytest's tests are in the package, run the tests!
      - python -c "import nbsmoke"
